### ISSUE TITLE
`daq_to_raw` segmentation fault at legend-login.lngs.infn.it

### ISSUE THREAD

**Issue by gipert** [legend-exp/pygama#200]
Something weird happens when I try to generate raw files for the latest SiPM data on legend-login.lngs.infn.it:
```
Pygama Data Processing Utility
  Running step       daq_to_raw
  Input  files:      /data1/shared/lar-commissioning/data/daq/com/sipmtest-202110/ch-0-11-amaj1-lowthr-3usec-trace.fcio
  Output directory:  /data1/shared/lar-commissioning/data/raw/com/sipmtest-202110
  Config file:       /data1/shared/lar-commissioning/software/meta/com/sipmtest-202110/d2r_config.json
  Max ev number:     inf
Output group : output file
spms/raw : ch-0-11-amaj1-lowthr-3usec-trace_raw.lh5
Progress : [###############-----] 73.4% Traceback (most recent call last):
  File "/data1/shared/lar-commissioning/software/pygama-v01/pygama-run.py", line 117, in <module>
    main()
  File "/data1/shared/lar-commissioning/software/pygama-v01/pygama-run.py", line 94, in main
    process_flashcam(f_input[i], f_output[i], ch_groups_dict=ch_groups,
  File "/data1/shared/lar-commissioning/software/pygama-v01/local/lib/python3.8/site-packages/pygama/io/fcdaq.py", line 481, in process_flashcam
    lh5_store.write_object(tbl, group_path, out_file, n_rows=tbl.loc)
  File "/data1/shared/lar-commissioning/software/pygama-v01/local/lib/python3.8/site-packages/pygama/lh5/store.py", line 515, in write_object
    self.write_object(obj[field], 
  File "/data1/shared/lar-commissioning/software/pygama-v01/local/lib/python3.8/site-packages/pygama/lh5/store.py", line 588, in write_object
    ds[-add_len:] = nda
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/data1/shared/lar-commissioning/software/pygama-v01/local/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 920, in __setitem__
    self.id.write(mspace, fspace, val, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 232, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 114, in h5py._proxy.dset_rw
OSError: [Errno 5] Can't write data (file read failed: time = Thu Oct 21 12:47:43 2021
, filename = '/data1/shared/lar-commissioning/data/raw/com/sipmtest-202110/ch-0-11-amaj1-lowthr-3usec-trace_raw.lh5', file descriptor = 5, errno = 5, error message = 'Input/output error', buf = 0x55e2f22a1818, total read size = 1736, bytes this sub-read = 1736, bytes actually read = 18446744073709551615, offset = 0)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (unable to close file, errno = 5, error message = 'Input/output error')
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (unable to close file, errno = 5, error message = 'Input/output error')
/data1/users/pertoldi/sw/src/legend/pygama/experiments/lar_commissioning/software/run-production.sh: line 22: 184957 Segmentation fault      "$local_sw/pygama-run.py" --verbose --step daq_to_raw --input-files "$fcio_files" --output-dir "$prod_base/raw/$run_name" --config-file "$meta_path/d2r_config.json" --overwrite
```
Seems to be somehow related to legend-login, since I don't get the error on e.g. lfs1.mpi-hd.mpg.de. Ideas?

**Comment by gipert** [comment]
I cannot reproduce this anymore with the new Ubuntu-based container and same pygama version. I've now converted several GBs of FlashCam files with no errors so far. Let's hope it was a bug in some of our dependencies. Closing.
