### ISSUE TITLE
Bug: file too big?

### ISSUE THREAD

**Issue by rosannadeckert** [legend-exp/pygama#204]
When I run my script on this dsp data I get a bug because the file is somehow to big...
```
/lfs/l1/legend/users/rdeckert/pygama/experiments/lar_commissioning/software > python scripts/wf-templates
loading data for /lfs/l1/legend/users/rdeckert/pygama/experiments/lar_commissioning/data/com/dsp/sipmtest-202110/singles-amaj1-250usec-trace_dsp.lh5
Traceback (most recent call last):
  File "scripts/wf-templates.py", line 66, in <module>
    wf_template(dsp, 0, 100)
  File "scripts/wf-templates.py", line 6, in wf_template
    df = lh5.load_nda(dsp_file, ['channel', 'wf_blsub', 'bl_slope', 'max_wf', 'vt_max_out','max_val_wf', 't0'],'spms/dsp')
  File "/lfs/l1/legend/users/rdeckert/pygama/experiments/lar_commissioning/software/.local/lib/python3.8/site-packages/pygama/lh5/store.py", line 686, in load_nda
    par_data = {par : np.concatenate(par_data[par]) for par in par_list}
  File "/lfs/l1/legend/users/rdeckert/pygama/experiments/lar_commissioning/software/.local/lib/python3.8/site-packages/pygama/lh5/store.py", line 686, in <dictcomp>
    par_data = {par : np.concatenate(par_data[par]) for par in par_list}
  File "<__array_function__ internals>", line 5, in concatenate
numpy.core._exceptions.MemoryError: Unable to allocate 84.7 GiB for an array with shape (11965002, 1900) and data type float32
```

**Comment by gipert** [comment]
CC @ninaburlac

**Comment by rosannadeckert** [comment]
Hi Jason, thanks for your answer. I tried to use `idx_list `but it seems that it is not implemented in pygama yet...

**Comment by jasondet** [comment]
🤦‍♂️

I'll go implement it.

**Comment by jasondet** [comment]
ok the fix has been implemented and merged into the master branch.
