### ISSUE TITLE
orcadaq io error

### ISSUE THREAD

**Issue by wcpettus** [legend-exp/pygama#205]
file_size is a float and will crash `daq2raw` because it eventually gets used in a `range`; recast here?
https://github.com/legend-exp/pygama/blob/master/pygama/io/orcadaq.py#L355

```
Beginning daq-to-raw processing ...
Traceback (most recent call last):
  File "./processing.py", line 378, in <module>
    main()
  File "./processing.py", line 81, in main
    if args.d2r: d2r(dg, args.over, nwfs, args.verbose, args.user)
  File "./processing.py", line 123, in d2r
    daq_to_raw(f_daq, f_raw, config=dg.config, systems=subs, verbose=verbose,
  File "/global/u2/p/pettus/pygama/pygama/io/daq_to_raw.py", line 86, in daq_to_raw
    process_orca(daq_filename, raw_file_pattern, n_max, ch_groups_dict, verbose, buffer_size=buffer_size)
  File "/global/u2/p/pettus/pygama/pygama/io/orcadaq.py", line 356, in process_orca
    progress_bar = tqdm_range(0, n_entries, text="Processing", verbose=verbose, unit=unit)
  File "/global/u2/p/pettus/pygama/pygama/utils.py", line 113, in tqdm_range
    return tqdm.trange(start, stop, step,
  File "/opt/anaconda3/lib/python3.8/site-packages/tqdm/std.py", line 1524, in trange
    return tqdm(_range(*args), **kwargs)
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by gipert** [comment]
Regression introduced by #203

**Comment by wisecg** [comment]
I just put in a change to the master branch to fix this.  Will also propagate it to the dev branch.

**Comment by wisecg** [comment]
Done

**Comment by wcpettus** [comment]
missed one:
https://github.com/legend-exp/pygama/blob/master/pygama/io/orcadaq.py#L356
please re-open
